# Needs the ip range in - docker network inspect -f '{{.IPAM.Config}}' kind
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.19.255.200-172.19.255.250
  # autoAssign: false
  # avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system


