---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - argocd-install.yaml
namespace: argocd
patches:
  - path: patches/argocd-cm-patch.yaml
    target:
      name: argocd-cm
  - path: patches/argocd-server-patch.yaml
    target:
      name: argocd-server
      kind: Deployment